/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorReservas;
import java.util.ArrayList;

/**
 *
 * @author Mata
 */
public class Reserva extends javax.swing.JFrame {

    
    ControladorReservas controlador;
  
    
    public Reserva() {
      controlador = new ControladorReservas(this);
      
      initComponents();
      controlador.cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        txtFecha = new javax.swing.JTextField();
        txtHoraInicio = new javax.swing.JTextField();
        txtHoraFin = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        comboRecursos = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalas = new javax.swing.JTable();
        btnReservar = new javax.swing.JButton();
        txtIdAReservar = new javax.swing.JTextField();
        label6 = new java.awt.Label();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("Salas disponibles");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 202, 53));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 123, 90, 32));
        getContentPane().add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 123, 90, 32));
        getContentPane().add(txtHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 123, 90, 32));

        label2.setText("Fecha A-M-D");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 93, -1, -1));

        label3.setText("Hora Inicio 00:00");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 93, -1, -1));

        label4.setText("Hora Fin 00:00");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 93, -1, -1));

        label5.setText("Recursos");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 93, -1, -1));

        comboRecursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno" }));
        getContentPane().add(comboRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 128, 129, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 127, -1, -1));

        tableSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Sala", "Ubicacion", "Capacidad", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tableSalas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 226, 561, 265));

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, -1));
        getContentPane().add(txtIdAReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 90, 40));

        label6.setText("Id de la sala a reservar: ");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      controlador.llenarTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
     controlador.abrirReserva();
    }//GEN-LAST:event_btnReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnReservar;
    public javax.swing.JComboBox<String> comboRecursos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    public javax.swing.JTable tableSalas;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtHoraFin;
    public javax.swing.JTextField txtHoraInicio;
    public javax.swing.JTextField txtIdAReservar;
    // End of variables declaration//GEN-END:variables
}
